### ISSUE TITLE
how would you write this simple example in calmm?

### ISSUE THREAD

**Issue by cag-oss** [calmm-js/documentation#6]
This example is from milankinen/react-reactive-toolkit.
I can't quite wrap my head around how to do this in calmm. Say I wanted to update two state atoms: searchText and repos. Is there a way to express the atoms as observables instead of .modify-ing them? When using observables as in the example, are you not even supposed to use any state? Or would I have to subscribe to seperate observables who are combined() from the atoms, and then via something like onValue() imperatively set the atom? That feels weird.

```javascript
import React from "react"
import Kefir from "kefir"
import R from "react.reactive"
import {render} from "react-dom"


const searchUrl = q =>
  `https://api.github.com/search/repositories?q=${q}&sort=stars&order=desc`

const GithubSearch = R(({events}) => {
  const searchText =
    Kefir.fromEvents(events, "searchText:changed")
      .map(e => e.target.value)
      .merge(Kefir.fromEvents(events, "searchText:clear").map(() => ""))
      .merge(Kefir.constant(""))  // initial value
      .toProperty()

  const repos =
    searchText
      .debounce(300)
      .map(encodeURIComponent)
      .flatMapLatest(q => q.length < 3
        ? Kefir.constant({items: []})
        : Kefir.fromPromise(fetch(searchUrl(q)).then(req => req.json()))
      )
      .map(res => res.items.map(it => ({
        id: it.id,
        name: it.full_name,
        stars: it.stargazers_count
      })))

  return (
    <div>
      <h1>Github Repository search</h1>
      <R.input placeholder="Repository name"
               emits={{change: "searchText:changed"}}
               value={searchText} />
      <R.button emits={{click: "searchText:clear"}}
                disabled={searchText.map(t => t.length === 0)}>
        Reset
      </R.button>
      <R.ul>
        {repos.map(repos => repos.map(({id, name, stars}) =>
          <li key={id}>
            {name} (stars: {stars})
          </li>
        ))}
      </R.ul>
    </div>
  )
})

render(<GithubSearch />, document.getElementById("app"))
```

**Comment by polytypic** [comment]
Perhaps this [Calmm GitHub Search example](https://stackblitz.com/edit/calmm-github-search) helps.

BTW, we were working on the same project with @milankinen when Calmm was born.

**Comment by cag-oss** [comment]
Thank you that's great, I somehow missed the first 2 links in the wiki.
It looks like the 'reset' button is broken, maybe just a leftover from a copy/paste of the 
original example.
I'm curious how you will handle the reset!

**Comment by polytypic** [comment]
I noticed I forgot to convert the reset button and I already fixed it a moment ago.

**Comment by polytypic** [comment]
BTW, if you are interested in learning Calmm, I recommend joining the [Gitter](https://gitter.im/calmm-js/chat) channel and asking question there.

**Comment by cag-oss** [comment]
very cool, I see how that works, just set the atom. So in your thinking, the request result doesn't need to be an atom or exist in state at all, its more of a derived value from the search text? Very interesting thank you for these samples.

**Comment by polytypic** [comment]
Yes and no problem. :)
