### ISSUE TITLE
given a stream or property encapsulating an http request, how would you execute it onMount, and how would you implement a refresh button?

### ISSUE THREAD

**Issue by cag-oss** [calmm-js/documentation#7]
given a stream like this:
```
const searchUrl  = `https://my.api/users`

const UsersPage = () => {
  const users = U.seq(
    ??? what goes here? Atom? EventEmitter? Bus?,
    U.debounce(300),
    U.flatMapLatest(q => q.length < 3
      ? {items: []}
      : Kefir.fromPromise(fetch(searchUrl).then(req => req.json()))),
    U.view('users'),
    U.map(it => ({
      id: it.id,
      name: it.full_name,
    })))

    return ({<button onClick={?????}>refresh</button> {listOfUsers(users)}
```

1) how would you execute this on mount? EventEmitter? Bus? Atom? Something else?
2) how would you implement a refresh button?

**Comment by polytypic** [comment]
How about joining the [Gitter](https://gitter.im/calmm-js/chat) channel where there are more people that could answer questions like this. :)

To execute on mount one would typically simply derive some property from the observable to embed on the VDOM.

If you really want an explicit refresh button, then you basically just need to make sure that an update bubbles through the chain.  There are several ways to do that.

```js
const refresh = U.atom(0)

const users = U.seq(
  U.template({query, refresh}),
  U.debounce(300),
  U.flatMapLatest(({query}) => query.length < 3
    ? {users: []}
    : Kefir.fromPromise(fetch(searchUrl(query)).then(req => req.json()))),
  U.view('users'),
  U.map(it => ({
    id: it.id,
    name: it.full_name,
  })))

<button onClick={() => refresh.modify(U.inc)}>refresh</button>
```

**Comment by polytypic** [comment]
BTW, instead of explicit refresh buttons, I would look into using e.g. websockets to push change notifications to clients.

**Comment by cag-oss** [comment]
thank you!
